### ISSUE TITLE
[FEAT] todo list에 todoItem을 키보드로 입력하여 추가하기

### ISSUE THREAD

**Issue by pje1740** [pje1740/js-todo-list-step1#2]
##  🗣 설명
todo list에 todoItem을 키보드로 입력하여 추가하기

## ✅ 체크리스트

- [x] todoItem 모듈 제작
- [x] 입력창 엔터 이벤트 추가
- [x] todo list에 리스트 아이템 추가 메소드 작성
