### ISSUE TITLE
[FEAT] todo list를 더블클릭했을 때 input 모드로 변경

### ISSUE THREAD

**Issue by pje1740** [pje1740/js-todo-list-step1#6]
##  🗣 설명

todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀

## ✅ 체크리스트

- [ ] 더블클릭 이벤트로 수정창 display 및 view display 끄기
- [ ] 엔터로 수정 적용
- [ ] esc키 입력 시 수정이 반영되지 않고 view display 켜기
